from enum import Enum


class Emoji(Enum):
    Error = '❌'
    Success = '✅'
    Warning = '⚠️'
    MainMenu = '🏠'
    ReportMenu = '🧾'
    MoreEmoji = '💬'
    Start = '▶️'
    ImageSize = '🖼'
    ElementPerImage = '🔲'
    Save = '💾'
    Seed = '🎲'
    Folder = '📁'
    Photo = '📷'
    Question = '❓'
    Settings = '⚙️'
    Refresh = '🔄'
    Statistics = '📊'
    Flask = '🧪'
    Stop = '⏸️'
    EditText = '✏️'
    ExperimentHistory = '📝'
    TechnicalSpecification = '📄'
    New = '🆕'
    Brain = '🧠'
    Delete = '🗑️'
    Cancel = '❎'
    RobotEmoji = '🤖'
    SicknessEmoji = '😷'
    VacationEmoji = '🌴'
    BusinessTripEmoji = '💼'
    EmployeeEmoji = '🧑‍💻'
    MakerEmoji = '👷🏼‍♂️'
    PenEmoji = '🖊️'
    WrenchEmoji = '🔧'
    CalendarEmoji = '📅'
    PeriodEmoji = '🗓'
    RightArrowEmoji = '➡️'
    DownArrowEmoji = '⬇️'
    CheckMarkEmoji = '📌'

    def __str__(self):
        return self.value
